name = "stripe-checkout-generator"
main = "src/stripe-checkout-generator.js"
compatibility_date = "2024-01-01"

[vars]
PWA_URL = "https://remarkable-capybara-1ec7f2.netlify.app"
LANDING_URL = "https://landing-edc.netlify.app"
MONTHLY_PRICE_ID = "price_1SiCmTIDgcZhXc4U1I7oaBN3"
YEARLY_PRICE_ID = "price_1SiCnMIDgcZhXc4UkpKVvoXu"
LOGO_FILE_ID = "file_1SiEPjIDgcZhXc4UB2B6GOgD"

# Secrets (set via: wrangler secret put STRIPE_API_KEY)
# STRIPE_API_KEY = "sk_test_..."
