name = "stripe-checkout-generator"
main = "src/stripe-checkout-generator.js"
compatibility_date = "2024-01-01"

[vars]
PWA_URL = "https://app.everydaychristian.app"
LANDING_URL = "https://everydaychristian.app"
# Price IDs (LIVE MODE)
YEARLY_TRIAL_PRICE_ID = "price_1SiF65IFwav1xmJDUpzR9qJD"
YEARLY_PRICE_ID = "price_1SiF64IFwav1xmJDtExdlpSZ"
MONTHLY_PRICE_ID = "price_1SiF64IFwav1xmJD04g0Vto2"
LOGO_FILE_ID = "file_1SiEtJIDgcZhXc4UNRS3GPFG"

# Secrets (set via: wrangler secret put STRIPE_API_KEY)
# STRIPE_API_KEY = "sk_test_..."
